-- Migration 009 — design_projects.site_plan_image_id
--
-- Adds a FK column referencing design_assets(sha256) so each project can
-- pin a single canonical "clean site plan" image. The cleaned plan is
-- generated by Nanobanana from the client's raw upload (PDF / sketch /
-- messy photo) via POST /api/design/ai_images/generate-site-plan and
-- serves as the base layer for downstream design packs.
--
-- SET NULL on delete: dropping the asset row (rare — assets are typically
-- shared across projects) shouldn't cascade-delete the project. The
-- partial index lets us cheaply list "projects with a site plan" without
-- bloating the index with NULL rows for the still-being-onboarded majority.

ALTER TABLE design_projects
  ADD COLUMN IF NOT EXISTS site_plan_image_id TEXT
    REFERENCES design_assets(sha256) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_design_projects_site_plan
  ON design_projects(site_plan_image_id) WHERE site_plan_image_id IS NOT NULL;
