'use strict';

// Auto-task emitter — implements Notion FAD scoping pack v0.1 §7.SS.
// Five server-side triggers spawn rows in design_tasks every 5 minutes
// (scheduler.js drives the cadence). Each emission is idempotent: a
// previously-emitted task with the same external_ref still open blocks
// re-emission; once the human marks it done, the slot is freed and the
// next scan will emit again if the underlying condition recurs.
//
// Dedup model
// ───────────
// Every auto-emitted task carries external_ref = "auto:<trigger>:<target>".
// Partial unique index in migration 007 enforces uniqueness across
// (project_id, external_ref) WHERE status <> 'done'. That covers race
// conditions across overlapping scheduler ticks; the SQL itself also
// LEFT-JOINs against open auto-tasks so we don't burn an insert just to
// hit a constraint violation. Belt and braces.
//
// Lifecycle filter
// ────────────────
// Paused / cancelled projects are excluded everywhere — there's no point
// nagging a design lead about a blocker on a project that's been parked.
//
// Activity log
// ────────────
// Each successful insert appends a `task.auto_created` activity (visibility
// internal) with payload {trigger, target_id}. This is the only notification
// surface for v0.1; GMS notifications fan-out is a separate slice.

const { pool, query } = require('../../database/client');
const { appendActivity } = require('../activities');

// ─── Gate → stage gate map (see Notion §7.SS, trigger 3) ──────────────
// A payment gate is "blocked" when its status is still pending but the
// project has already entered (or passed) the stage that should have
// required it as a prerequisite. STAGES (frontend/src/app/fad/_data/design.ts)
// is the single source of truth for ordering; we mirror it here to avoid
// pulling the frontend module into the backend.
//
// Gates not listed (e.g. agreement_signed) are gated by entering the
// FIRST stage past their threshold. The threshold stage_key is the EARLIEST
// stage at which the gate is considered overdue.
const GATE_THRESHOLD_STAGE = {
  agreement_signed: 'payment-gate',
  design_fee_60: 'moodboard',
  design_fee_40: 'final-budget',
  execution_fee_t1: 'execution',
  execution_fee_t2: 'execution',
  project_funds: 'execution',
  final_balance: 'reconciliation',
};

// Mirror of STAGES[].index for the 17 design stages. Kept inline so this
// module has no frontend dependency. Update in lock-step with design.ts.
const STAGE_INDEX = {
  lead: 1,
  proposal: 2,
  'doc-request': 3,
  'site-visit': 4,
  preferences: 5,
  'rough-budget': 6,
  agreement: 7,
  signature: 8,
  'payment-gate': 9,
  moodboard: 10,
  'design-pack': 11,
  'design-review': 12,
  'final-budget': 13,
  'funding-gate': 14,
  execution: 15,
  'expense-capture': 16,
  reconciliation: 17,
};

const TRIGGERS = [
  'blocker',
  'approval_stale',
  'payment_blocked',
  'budget_variance',
  'task_overdue',
];

/**
 * Resolve the user_id of the Finance role-holder. Best-effort: if there
 * are multiple finance users, returns the first by name. If there are
 * none, returns null and the auto-task is created unassigned — Finance
 * surface picks it up via the tasks board with status=todo, assignee=null.
 */
async function findFinanceUserId() {
  try {
    const { rows } = await pool.query(
      `SELECT id FROM users
       WHERE role = 'finance' AND is_active = true
       ORDER BY display_name NULLS LAST
       LIMIT 1`,
    );
    return rows[0]?.id || null;
  } catch (e) {
    // The users table lives in the GMS schema; if it's not present in
    // this deployment (some dev DBs) we degrade silently rather than
    // failing the whole scan.
    console.warn('[auto-tasks] Finance role lookup failed:', e.message);
    return null;
  }
}

/**
 * Insert a single auto-task row + append a task.auto_created activity.
 * Idempotent via external_ref + the partial unique index from migration
 * 007. Returns the inserted row id, or null if it was a duplicate.
 */
async function emitTask({ projectId, trigger, targetId, title, assigneeUserId, stageKey }) {
  const externalRef = `auto:${trigger}:${targetId}`;
  // INSERT … ON CONFLICT DO NOTHING — the partial unique index handles
  // the race between concurrent scheduler ticks. Returning ID tells us
  // whether the insert actually happened (versus being suppressed).
  const { rows } = await query(
    `INSERT INTO design_tasks (project_id, title, assignee_user_id, stage_key, status, notes, external_ref)
     VALUES ($1, $2, $3, $4, 'todo', $5, $6)
     ON CONFLICT (project_id, external_ref) WHERE external_ref IS NOT NULL AND status <> 'done'
     DO NOTHING
     RETURNING id`,
    [
      projectId,
      title,
      assigneeUserId || null,
      stageKey || null,
      `[auto:${trigger}:${targetId}] generated by the auto-task scanner; resolve and mark done.`,
      externalRef,
    ],
  );
  if (rows.length === 0) return null;
  await appendActivity({
    projectId,
    actorUserId: null,
    actorName: 'auto-task scanner',
    action: 'task.auto_created',
    payload: { trigger, target_id: targetId, task_id: rows[0].id, external_ref: externalRef },
    visibility: 'internal',
  }).catch((e) => {
    // Activity log is non-fatal — the task is already in place.
    console.warn('[auto-tasks] activity append failed:', e.message);
  });
  return rows[0].id;
}

// ─── Trigger 1: stage-transition blocker held >24h ────────────────────
//
// design_projects.blocker is a free-text field set when the design lead
// flags a project as stuck. We can't tell from blocker alone how long
// it's been there; updated_at on the project flips on every row change.
// Approximation: any project whose blocker is non-null AND updated_at is
// >24h old is treated as stale. False positives are tolerable (the lead
// has been editing other fields more recently than the blocker), false
// negatives are not (we want noisy nagging).
//
// Target id: the project_id itself. One stale-blocker task per project.
async function runBlockerTrigger() {
  const { rows } = await query(
    `SELECT p.id, p.blocker, p.design_lead_user_id
     FROM design_projects p
     LEFT JOIN design_tasks t
       ON t.project_id = p.id
      AND t.external_ref = 'auto:blocker:' || p.id::text
      AND t.status <> 'done'
     WHERE p.tenant_id = $1
       AND p.lifecycle_status = 'active'
       AND p.blocker IS NOT NULL
       AND p.blocker <> ''
       AND p.updated_at < NOW() - INTERVAL '24 hours'
       AND t.id IS NULL`,
    ['00000000-0000-0000-0000-000000000001'],
  );
  let n = 0;
  for (const r of rows) {
    const id = await emitTask({
      projectId: r.id,
      trigger: 'blocker',
      targetId: r.id,
      title: `Resolve blocker: ${r.blocker}`,
      assigneeUserId: r.design_lead_user_id,
    });
    if (id) n++;
  }
  return n;
}

// ─── Trigger 2: owner approval pending >7 days ────────────────────────
//
// design_approvals.sent_at is the clock-start. status='pending' for >7d
// → chase task. One open chase per approval.
//
// Target id: the approval_id. Title leans on .type so the lead knows
// which artefact (moodboard / pack / change-order / ...) is the holdup.
async function runApprovalStaleTrigger() {
  const { rows } = await query(
    `SELECT a.id, a.project_id, a.type, p.design_lead_user_id
     FROM design_approvals a
     JOIN design_projects p ON p.id = a.project_id
     LEFT JOIN design_tasks t
       ON t.project_id = a.project_id
      AND t.external_ref = 'auto:approval_stale:' || a.id::text
      AND t.status <> 'done'
     WHERE p.tenant_id = $1
       AND p.lifecycle_status = 'active'
       AND a.status = 'pending'
       AND a.sent_at < NOW() - INTERVAL '7 days'
       AND t.id IS NULL`,
    ['00000000-0000-0000-0000-000000000001'],
  );
  let n = 0;
  for (const r of rows) {
    const id = await emitTask({
      projectId: r.project_id,
      trigger: 'approval_stale',
      targetId: r.id,
      title: `Chase owner on ${r.type}`,
      assigneeUserId: r.design_lead_user_id,
    });
    if (id) n++;
  }
  return n;
}

// ─── Trigger 3: payment gate blocked by stage progression ─────────────
//
// A gate is "blocked" when it's still pending despite the project having
// crossed the threshold stage that gate is supposed to predicate. The
// canonical example is design_fee_60 pending while the project is in
// moodboard stage — owner is consuming work product they haven't paid
// for. Assignee is the Finance role-holder (looked up once per scan).
//
// Target id: the gate row id. One Finance task per blocked gate.
async function runPaymentBlockedTrigger(financeUserId) {
  // Compute thresholds inline so the SQL stays driven by a single
  // VALUES list rather than 7 separate queries.
  const thresholdRows = Object.entries(GATE_THRESHOLD_STAGE).map(
    ([gate, stage]) => `('${gate}', ${STAGE_INDEX[stage]})`,
  ).join(', ');

  const { rows } = await query(
    `WITH gate_thresholds(gate_id, threshold_index) AS (VALUES ${thresholdRows}),
          stage_index(stage_key, idx) AS (VALUES
            ('lead', 1), ('proposal', 2), ('doc-request', 3), ('site-visit', 4),
            ('preferences', 5), ('rough-budget', 6), ('agreement', 7),
            ('signature', 8), ('payment-gate', 9), ('moodboard', 10),
            ('design-pack', 11), ('design-review', 12), ('final-budget', 13),
            ('funding-gate', 14), ('execution', 15), ('expense-capture', 16),
            ('reconciliation', 17)
          )
     SELECT g.id, g.project_id, g.gate_id
     FROM design_payment_gates g
     JOIN design_projects p ON p.id = g.project_id
     JOIN gate_thresholds gt ON gt.gate_id = g.gate_id
     JOIN stage_index si ON si.stage_key = p.current_stage
     LEFT JOIN design_tasks t
       ON t.project_id = g.project_id
      AND t.external_ref = 'auto:payment_blocked:' || g.id::text
      AND t.status <> 'done'
     WHERE p.tenant_id = $1
       AND p.lifecycle_status = 'active'
       AND g.status = 'pending'
       AND si.idx >= gt.threshold_index
       AND t.id IS NULL`,
    ['00000000-0000-0000-0000-000000000001'],
  );
  let n = 0;
  for (const r of rows) {
    const id = await emitTask({
      projectId: r.project_id,
      trigger: 'payment_blocked',
      targetId: r.id,
      title: `Payment gate blocked: ${r.gate_id}`,
      assigneeUserId: financeUserId,
    });
    if (id) n++;
  }
  return n;
}

// ─── Trigger 4: budget item over the rough-budget line by >15% ────────
//
// design_budget_items × design_rough_budgets join on category_code: if
// a procurement line beats its rough estimate by >15% we want a budget
// variance task on the design lead. "Corresponding rough_budget line"
// is matched by category_code. Multiple budget items per category roll
// up: we compare aggregate item cost vs aggregate rough cost.
//
// Target id: the FIRST budget_item id in the group (the row that pushed
// the aggregate over). Keeps the task surface from blowing up when many
// small items share a category.
async function runBudgetVarianceTrigger() {
  const { rows } = await query(
    `WITH items_by_cat AS (
       SELECT b.project_id,
              b.category_code,
              SUM(b.unit_cost_minor * b.quantity) AS item_total,
              MIN(b.id::text) AS first_item_id,
              MIN(b.description) AS sample_description
       FROM design_budget_items b
       WHERE b.category_code IS NOT NULL
         AND b.unit_cost_minor IS NOT NULL
         AND b.quantity IS NOT NULL
       GROUP BY b.project_id, b.category_code
     ),
     rough_by_cat AS (
       SELECT project_id, category_code,
              SUM(unit_cost_minor * quantity) AS rough_total
       FROM design_rough_budgets
       WHERE category_code IS NOT NULL
         AND unit_cost_minor IS NOT NULL
         AND quantity IS NOT NULL
       GROUP BY project_id, category_code
     )
     SELECT i.project_id,
            i.category_code,
            i.first_item_id::uuid AS target_id,
            i.sample_description,
            p.design_lead_user_id,
            i.item_total,
            r.rough_total
     FROM items_by_cat i
     JOIN rough_by_cat r
       ON r.project_id = i.project_id AND r.category_code = i.category_code
     JOIN design_projects p ON p.id = i.project_id
     LEFT JOIN design_tasks t
       ON t.project_id = i.project_id
      AND t.external_ref = 'auto:budget_variance:' || i.first_item_id
      AND t.status <> 'done'
     WHERE p.tenant_id = $1
       AND p.lifecycle_status = 'active'
       AND r.rough_total > 0
       AND i.item_total > r.rough_total * 1.15
       AND t.id IS NULL`,
    ['00000000-0000-0000-0000-000000000001'],
  );
  let n = 0;
  for (const r of rows) {
    const desc = r.sample_description || r.category_code;
    const id = await emitTask({
      projectId: r.project_id,
      trigger: 'budget_variance',
      targetId: r.target_id,
      title: `Budget variance: ${desc}`,
      assigneeUserId: r.design_lead_user_id,
    });
    if (id) n++;
  }
  return n;
}

// ─── Trigger 5: in-progress task overdue by >7 days ───────────────────
//
// Self-recursive — design_tasks itself is the source. Tasks in
// status='in_progress' with due_date older than NOW()-7d spawn a
// follow-up "Overdue: <original title>" task. The follow-up's
// external_ref pins to the ORIGINAL task id so we only emit one
// reminder per stuck task. To avoid creating a cascade (overdue → new
// task → new task is overdue → ...) we filter out auto-tasks themselves
// (external_ref starting with 'auto:task_overdue:') as candidates.
//
// Assignee inherits from the original task. Stage_key inherits too.
async function runTaskOverdueTrigger() {
  const { rows } = await query(
    `SELECT orig.id, orig.project_id, orig.title,
            orig.assignee_user_id, orig.stage_key
     FROM design_tasks orig
     JOIN design_projects p ON p.id = orig.project_id
     LEFT JOIN design_tasks t
       ON t.project_id = orig.project_id
      AND t.external_ref = 'auto:task_overdue:' || orig.id::text
      AND t.status <> 'done'
     WHERE p.tenant_id = $1
       AND p.lifecycle_status = 'active'
       AND orig.status = 'in_progress'
       AND orig.due_date IS NOT NULL
       AND orig.due_date < NOW() - INTERVAL '7 days'
       AND (orig.external_ref IS NULL OR orig.external_ref NOT LIKE 'auto:task_overdue:%')
       AND t.id IS NULL`,
    ['00000000-0000-0000-0000-000000000001'],
  );
  let n = 0;
  for (const r of rows) {
    const id = await emitTask({
      projectId: r.project_id,
      trigger: 'task_overdue',
      targetId: r.id,
      title: `Overdue: ${r.title}`,
      assigneeUserId: r.assignee_user_id,
      stageKey: r.stage_key,
    });
    if (id) n++;
  }
  return n;
}

/**
 * Run all five trigger queries in sequence and return a summary.
 *
 * Each trigger swallows its own errors and returns 0 if it failed —
 * one broken trigger shouldn't take down the rest of the scan. The
 * scheduler logs the summary on every tick.
 */
async function runAutoTaskScan() {
  const byTrigger = { blocker: 0, approval_stale: 0, payment_blocked: 0, budget_variance: 0, task_overdue: 0 };
  let financeUserId = null;
  try {
    financeUserId = await findFinanceUserId();
  } catch (e) {
    console.warn('[auto-tasks] Finance lookup failed (continuing):', e.message);
  }

  const runners = [
    ['blocker', runBlockerTrigger],
    ['approval_stale', runApprovalStaleTrigger],
    ['payment_blocked', () => runPaymentBlockedTrigger(financeUserId)],
    ['budget_variance', runBudgetVarianceTrigger],
    ['task_overdue', runTaskOverdueTrigger],
  ];

  for (const [name, fn] of runners) {
    try {
      byTrigger[name] = await fn();
    } catch (e) {
      console.error(`[auto-tasks] trigger ${name} failed:`, e.message);
      byTrigger[name] = 0;
    }
  }

  const generated = Object.values(byTrigger).reduce((a, b) => a + b, 0);
  return { generated, by_trigger: byTrigger };
}

module.exports = {
  runAutoTaskScan,
  // Exported for tests / one-shot admin endpoint.
  TRIGGERS,
  GATE_THRESHOLD_STAGE,
  STAGE_INDEX,
};
